export const htmlRoutes = [
  '/',
  '/about',
  '/all-posts',
  '/authentic-artistique-endevours',
  '/blog',
  '/blog/event-delegation',
  '/contact-success',
  '/installations/magic-sprinkles',
  '/links',
  '/projects',
  '/secrets',
  '/snippets',
  '/snippets/use-copy-react',
  '/uses',
] as const

export const emptyProjectRoutes = [
  '/projects/aqrm',
  '/projects/clinically-relevant',
  '/projects/clr',
  '/projects/coolors-go',
  '/projects/dfrm',
  '/projects/fight-for-tribeland',
  '/projects/game-of-life',
  '/projects/jupyter-js',
  '/projects/magic-sprinkles',
  '/projects/not-messenger',
  '/projects/pokelife',
  '/projects/prompt-racer',
  '/projects/sizes',
  '/projects/slidy',
  '/projects/url-shortener-go',
  '/projects/wordle-score',
] as const

export const redirectContracts = [
  ['/blogs/promise-all', '/blog/promise-all', 308],
  ['/posts/promise-all', '/blog/promise-all', 308],
  ['/post/promise-all', '/blog/promise-all', 308],
  ['/p/promise-all', '/blog/promise-all', 308],
  ['/s/use-copy-react', '/snippets/use-copy-react', 308],
  ['/snippet/use-copy-react', '/snippets/use-copy-react', 308],
  ['/cypress', '/snippets/cypress', 307],
  ['/enzyme', '/snippets/enzyme', 307],
  ['/diy-promise-all', '/blog/promise-all', 307],
  ['/art', '/authentic-artistique-endevours', 307],
  ['/installations', '/authentic-artistique-endevours', 307],
  ['/contact', '/?ref=/contact#contact', 307],
  ['/src', 'https://github.com/soorria/soorria.com', 307],
  ['/stats', 'https://plausible.mooth.tech/mooth.tech', 307],
] as const
